import net.orhanbalci.fuzzymoea.db.Db;
import net.orhanbalci.fuzzymoea.entity.Food;
import net.orhanbalci.fuzzymoea.entity.Nutrient;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
  public String getGreeting() {
    return "Hello world.";
  }

  public void testDb() {
    Db db = new Db();
    for (Nutrient f : db.getNutrients()) {
      System.out.println(f.getName());
      System.out.println(f.getNutrientGroup().getName());
    }
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    new App().testDb();
  }
}
