import net.orhanbalci.fuzzymoea.db.Db;
import net.orhanbalci.fuzzymoea.entity.Nutrient;
import net.orhanbalci.fuzzymoea.experiment.DietPermutationExperiment;
import net.orhanbalci.fuzzymoea.experiment.MembershipFunctionExperiment;
import net.orhanbalci.fuzzymoea.fuzzy.FuzzyCalculator;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
  public String getGreeting() {
    return "Hello world.";
  }

  public void testDb() {
    Db db = new Db();
    for (Nutrient f : db.getNutrients()) {
      System.out.println(f.getName());
      System.out.println(f.getNutrientGroup().getName());
    }
  }

  public void generateData() {
    Db db = new Db();
    db.generateMissingFields();
  }

  public void testFuzzyCalculator(String controlFileName) {
    FuzzyCalculator fc = new FuzzyCalculator(controlFileName);
    fc.showCharts(3, 45, 7);
  }

  public static void main(String[] args) {
    //System.out.println(new App().getGreeting());
    //new App().generateData();
    //DietRunner.run();
    // App a = new App();

    // a.testFuzzyCalculator("diet_gaussian.fcl");
    // a.testFuzzyCalculator("diet.fcl");

    //DietPermutationRunner.run();
    //experimentMutationOperator();
    experimentMembershipFunction();
  }

  public static void experimentMutationOperator() {
    try {
      new DietPermutationExperiment(5, "MutationOperatorExperiment", 5, "child").run();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  public static void experimentMembershipFunction() {
    try {
      new MembershipFunctionExperiment(5, "MembershipFunctionExperiment", 5, "child").run();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
