import net.orhanbalci.fuzzymoea.db.Db;
import net.orhanbalci.fuzzymoea.entity.Nutrient;
import net.orhanbalci.fuzzymoea.experiment.DietPermutationExperiment;
import net.orhanbalci.fuzzymoea.experiment.GenerationCountExperiment;
import net.orhanbalci.fuzzymoea.experiment.MembershipFunctionExperiment;
import net.orhanbalci.fuzzymoea.experiment.MutationRateExperiment;
import net.orhanbalci.fuzzymoea.experiment.PreperationTimeExperiment;
import net.orhanbalci.fuzzymoea.experiment.PreperationTimeWithLikeExperiment;
import net.orhanbalci.fuzzymoea.fuzzy.FuzzyCalculator;
import net.orhanbalci.fuzzymoea.util.SolutionPrinter;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
  public String getGreeting() {
    return "Hello world.";
  }

  public void testDb() {
    Db db = new Db();
    for (Nutrient f : db.getNutrients()) {
      System.out.println(f.getName());
      System.out.println(f.getNutrientGroup().getName());
    }
  }

  public void generateData() {
    Db db = new Db();
    db.generateMissingFields();
  }

  public void testFuzzyCalculator(String controlFileName) {
    FuzzyCalculator fc = new FuzzyCalculator(controlFileName);
    fc.showCharts(3, 45, 7);
  }

  public static void main(String[] args) {
    //System.out.println(new App().getGreeting());
    //new App().generateData();
    //DietRunner.run();
    // App a = new App();

    // a.testFuzzyCalculator("diet_gaussian.fcl");
    // a.testFuzzyCalculator("diet.fcl");Pp

    //DietPermutationRunner.run();
    //experimentMutationOperator();
    //experimentMembershipFunction();
    //experimentMutationRate();
    //experimentGenerationCount();
    //experimentPreperationTime();
    //experimentPreperationTimeWithLike();
    convertSolutionFile();
  }

  public static void convertSolutionFile() {
    SolutionPrinter sp = new SolutionPrinter("male", 25);
    sp.convertSolution(
        "./PreperationTimeExperiment/PreperationTimeExperiment/data/NSGAII/DietProblemLongPreperationTime/MEDIAN_HV_VAR.tsv",
        "MEDIAN_HV_LONG.tsv",
        "MEDIAN_HV_LONG.time");
    sp.convertSolution(
        "./PreperationTimeExperiment/PreperationTimeExperiment/data/NSGAII/DietProblemShortPreperationTime/MEDIAN_HV_VAR.tsv",
        "MEDIAN_HV_SHORT.tsv",
        "MEDIAN_HV_SHORT.time");
  }

  public static void experimentMutationOperator() {
    try {
      new DietPermutationExperiment(5, "MutationOperatorExperiment", 25, "male").run();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  public static void experimentMembershipFunction() {
    try {
      new MembershipFunctionExperiment(5, "MembershipFunctionExperiment", 25, "male").run();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  public static void experimentMutationRate() {
    try {
      new MutationRateExperiment(20, "MutationRateExperiment", 25, "male").run();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  public static void experimentGenerationCount() {
    try {
      new GenerationCountExperiment(20, "GenerationCountExperiment", 25, "male").run();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  public static void experimentPreperationTime() {
    try {
      new PreperationTimeExperiment(20, "PreperationTimeExperiment", 25, "male").run();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  public static void experimentPreperationTimeWithLike() {
    try {
      new PreperationTimeWithLikeExperiment(20, "PreperationTimeWithLikeExperiment", 25, "male")
          .run();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
